"""empty message

Revision ID: cfebdc003489
Revises: 0e549f1a5814
Create Date: 2023-10-08 22:57:01.556804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfebdc003489'
down_revision = '0e549f1a5814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_date', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.String(length=80), nullable=False),
    sa.Column('event_location', sa.String(length=80), nullable=False),
    sa.Column('event_description', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_name', sa.String(length=80), nullable=False))
        batch_op.create_foreign_key(None, 'Events', ['event_id'], ['id'])

    with op.batch_alter_table('Magic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Magic', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('description')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_name')
        batch_op.drop_column('event_id')

    op.drop_table('Events')
    # ### end Alembic commands ###
